### ISSUE TITLE
Encoding the list of layers

### ISSUE THREAD

**Issue by infrontofthepark** [hupe13/leaflet-permalink#1]
Good move with the new version.

Would there be an efficient way to encode the list of active layers? 

Even better: with also markers selected?

Thank you!

**Comment by hupe13** [comment]
I'm sorry, I don't understand what you mean at all. What do you want to do with this plugin?

**Comment by infrontofthepark** [comment]
I would like to be able to share URLs containing not only the zoom and centre of the map, but also the selection of base maps and overlay maps that are active when I generate the URL.

**Comment by hupe13** [comment]
It may be that this is in some way possible, but not with this plugin.

**Comment by infrontofthepark** [comment]
I was just wondering if you had any plan to add this functionality. It would be great…

**Comment by hupe13** [comment]
There are so many ways to design maps. I can imagine that there is a solution for the individual. But that it is valid for all cases - not.
